version: "3.7"

services:
  api:
    build: .
    platform: "linux/amd64"
    tty: true
    volumes:
      - type: bind
        source: .
        target: /api
    command: yarn start:dev
    ports:
      - "3000:3000"
